INSERT INTO D_CTRL_PROCES_PARE (ID_PROCES_PARE, DES_PROCES_PARE)
VALUES (907, 'MODUL CPP');


INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (907, 'MODUL CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (61, 'TAULA INI GPP CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (62, 'TAULA INI GPP_EXP CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (63, 'TAULA INI EXP_SUBJECTE CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (64, 'TAULA INI EXP_OBJECTE CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (65, 'TAULA INI GPP_FASES CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (66, 'TAULA INI GPA_EXP CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (67, 'TAULA INI GPA_EXP_SUBJECTE CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (68, 'TAULA INI GPA_EXP_OBJECTES CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (69, 'TAULA INI GPA_EXP_OBJECTES CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (70, 'TAULA INI GPA_FASES CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (71, 'TAULA INI GPA_FASES_GRUP CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (72, 'TAULES DWH CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (73, 'TAULES DWH DS CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (74, 'TAULES DWH D CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (75, 'TAULES DWH F CPP' , 907);

INSERT INTO D_CTRL_PROCES (ID_PROCES, DES_PROCES, ID_PROCES_PARE)
VALUES (76, 'TAULA DT_ETL_DIA CPP' , 907);



--------------------------------------------------------
--  DDL for Table FS_OGC_EXPEDIENT
--------------------------------------------------------
DROP TABLE "DWH_FI"."FS_OGC_EXPEDIENT";

  CREATE TABLE "DWH_FI"."FS_OGC_EXPEDIENT" 
   (	"DT_ETL" NUMBER(*,0), 
	"DT_ETL_DIA" VARCHAR2(20 BYTE), 
	"ANY_EXPEDIENT" NUMBER(*,0) DEFAULT -1, 
	"NUM_EXPEDIENT" NUMBER(*,0) DEFAULT -1, 
	"WID_ENS" NUMBER(*,0) DEFAULT -1, 
	"WID_SUBJECTE" NUMBER(*,0) DEFAULT -1, 
	"WID_PRECEPTE" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOGRAFIA" NUMBER(*,0) DEFAULT -1, 
	"WID_AGENT1" NUMBER(*,0) DEFAULT -1, 
	"WID_AGENT2" NUMBER(*,0) DEFAULT -1, 
	"WID_FASE" NUMBER(*,0) DEFAULT -1, 
	"WID_ESTAT_TRAMITACIO" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOLOCALITZACIO" NUMBER(*,0) DEFAULT -1, 
	"EXPEDIENT_VIU" NUMBER(*,0), 
	"DT_DENUNCIA" NUMBER(*,0), 
	"HORA_DENUNCIA" VARCHAR2(12 BYTE), 
	"DT_FI_EXPEDIENT" NUMBER(*,0), 
	"DT_FASE" NUMBER(*,0), 
	"TIPUS_DENUNCIA" NUMBER(*,0), 
	"IDENTIFICAT" NUMBER(*,0), 
	"AMPLI_CARRER_DE" VARCHAR2(40 BYTE), 
	"CASA_DE" VARCHAR2(15 BYTE), 
	"AMPLI_EMISSOR_DE" VARCHAR2(40 BYTE), 
	"INSTR_DILIGENCIES" NUMBER(*,0), 
    "NUM_BUTLLETI" NUMBER(10,0),
	"I_DEUTE" NUMBER(11,2), 
	"I_SANCIO" NUMBER(11,2), 
	"DESCOMPTE" NUMBER(*,0), 
	"I_PAGAT" NUMBER(11,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;
--------------------------------------------------------
--  Constraints for Table FS_OGC_EXPEDIENT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_GEOLOCALITZACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_ESTAT_TRAMITACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_FASE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_AGENT2" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_AGENT1" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_PRECEPTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_SUBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("WID_ENS" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("DT_ETL_DIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_OGC_EXPEDIENT" MODIFY ("DT_ETL" NOT NULL ENABLE);
  
  
--------------------------------------------------------
--  DDL for Table F_OGC_EXPEDIENT
--------------------------------------------------------
DROP TABLE "DWH_FI"."F_OGC_EXPEDIENT";

  CREATE TABLE "DWH_FI"."F_OGC_EXPEDIENT" 
   (	"DT_ETL" NUMBER(*,0), 
	"DT_ETL_DIA" VARCHAR2(20 BYTE), 
	"ANY_EXPEDIENT" NUMBER(*,0) DEFAULT -1, 
	"NUM_EXPEDIENT" NUMBER(*,0) DEFAULT -1, 
	"WID_ENS" NUMBER(*,0) DEFAULT -1, 
	"WID_SUBJECTE" NUMBER(*,0) DEFAULT -1, 
	"WID_PRECEPTE" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOGRAFIA" NUMBER(*,0) DEFAULT -1, 
	"WID_AGENT1" NUMBER(*,0) DEFAULT -1, 
	"WID_AGENT2" NUMBER(*,0) DEFAULT -1, 
	"WID_FASE" NUMBER(*,0) DEFAULT -1, 
	"WID_ESTAT_TRAMITACIO" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOLOCALITZACIO" NUMBER(*,0) DEFAULT -1, 
	"EXPEDIENT_VIU" NUMBER(*,0), 
	"DT_DENUNCIA" NUMBER(*,0), 
	"HORA_DENUNCIA" VARCHAR2(12 BYTE), 
	"DT_FI_EXPEDIENT" NUMBER(*,0), 
	"DT_FASE" NUMBER(*,0), 
	"TIPUS_DENUNCIA" NUMBER(*,0), 
	"IDENTIFICAT" NUMBER(*,0), 
	"AMPLI_CARRER_DE" VARCHAR2(40 BYTE), 
	"CASA_DE" VARCHAR2(15 BYTE), 
	"AMPLI_EMISSOR_DE" VARCHAR2(40 BYTE), 
	"INSTR_DILIGENCIES" NUMBER(*,0), 
    "NUM_BUTLLETI" NUMBER(10,0),
	"I_DEUTE" NUMBER(11,2), 
	"I_SANCIO" NUMBER(11,2), 
	"DESCOMPTE" NUMBER(*,0), 
	"I_PAGAT" NUMBER(11,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" 
  PARTITION BY LIST ("DT_ETL") 
 (PARTITION "LOAD_20191128"  VALUES ('20191128') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ) ;
--------------------------------------------------------
--  Constraints for Table F_OGC_EXPEDIENT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_GEOLOCALITZACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_ESTAT_TRAMITACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_FASE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_AGENT2" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_AGENT1" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_PRECEPTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_SUBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("WID_ENS" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("DT_ETL_DIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_OGC_EXPEDIENT" MODIFY ("DT_ETL" NOT NULL ENABLE);
  
  
  
  
--------------------------------------------------------
--  DDL for Table TMP_OGC_EXPEDIENT_AMPLIADA
--------------------------------------------------------
DROP TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA";

  CREATE TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" 
   (	"ID_ENS" NUMBER(*,0), 
	"ANY_EXP" NUMBER(*,0), 
	"NUM_EXP" NUMBER(*,0), 
	"DT_EXPEDIENT" NUMBER(*,0), 
	"HORA_EXPEDIENT" VARCHAR2(12 BYTE), 
	"I_SANCIO" NUMBER(11,2), 
	"I_DEUTE" NUMBER(11,2), 
	"DESCOMPTE" NUMBER(*,0), 
	"TIPUS_DENUNCIA" NUMBER(*,0), 
	"IDENTIFICAT" NUMBER(*,0), 
	"NIF_AGENT1" VARCHAR2(9 BYTE), 
	"DES_AGENT1" VARCHAR2(40 BYTE), 
	"NIF_AGENT2" VARCHAR2(9 BYTE), 
	"DES_AGENT2" VARCHAR2(40 BYTE), 
	"ID_FASE" NUMBER(*,0), 
	"DT_FASE" NUMBER(*,0), 
	"DT_FI_EXP" NUMBER(*,0), 
	"ID_VIAL_DE" NUMBER(*,0), 
	"ID_SIGLES_DE" VARCHAR2(2 BYTE), 
	"CARRER_DE" VARCHAR2(30 BYTE), 
	"AMPLI_CARRER_DE" VARCHAR2(40 BYTE), 
	"CASA_DE" VARCHAR2(15 BYTE), 
	"AMPLI_EMISSOR_DE" VARCHAR2(40 BYTE), 
	"INSTR_DILIGENCIES" NUMBER(*,0), 
    "NUM_BUTLLETI" NUMBER(10,0), 
	"I_PAGAT" NUMBER(11,2), 
	"LITERAL" VARCHAR2(25 BYTE), 
	"NOM_COMPLET" VARCHAR2(100 BYTE), 
	"ESTAT_TRAMITACIO" NUMBER(*,0), 
	"EXPEDIENT_VIU" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;
--------------------------------------------------------
--  Constraints for Table TMP_OGC_EXPEDIENT_AMPLIADA
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("EXPEDIENT_VIU" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("ESTAT_TRAMITACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("NOM_COMPLET" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("LITERAL" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("ID_VIAL_DE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("ID_FASE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("DES_AGENT1" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("NUM_EXP" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("ANY_EXP" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_OGC_EXPEDIENT_AMPLIADA" MODIFY ("ID_ENS" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table FS_GIM_EXPEDIENT
--------------------------------------------------------
DROP TABLE "DWH_FI"."FS_GIM_EXPEDIENT";

  CREATE TABLE "DWH_FI"."FS_GIM_EXPEDIENT" 
   (	"DT_ETL" NUMBER(*,0), 
	"DT_ETL_DIA" VARCHAR2(20 BYTE), 
	"ANY_EXPEDIENT" NUMBER(*,0), 
	"NUM_EXPEDIENT" NUMBER(*,0), 
	"WID_ENS" NUMBER(*,0) DEFAULT -1, 
	"WID_SUBJECTE" NUMBER(*,0) DEFAULT -1, 
	"WID_PRECEPTE" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOGRAFIA" NUMBER(*,0) DEFAULT -1, 
	"WID_AGENT" NUMBER(*,0) DEFAULT -1, 
	"WID_FASE" NUMBER(*,0) DEFAULT -1, 
	"WID_ESTAT_TRAMITACIO" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOLOCALITZACIO" NUMBER(*,0) DEFAULT -1, 
	"DT_DENUNCIA" NUMBER(*,0), 
	"HORA_DENUNCIA" VARCHAR2(12 BYTE), 
	"FHORA_DENUNCIA" VARCHAR2(2 BYTE), 
	"DES_MARCA" VARCHAR2(40 BYTE), 
	"ID_MATRICULA" VARCHAR2(12 BYTE), 
	"TIPUS_DENUNCIA" NUMBER(*,0), 
	"CASA_DE" VARCHAR2(15 BYTE), 
    "NUM_BUTLLETI" NUMBER(10,0),
	"I_DEUTE" NUMBER(11,2), 
	"I_SANCIO" NUMBER(11,2), 
	"I_PAGAT" NUMBER(11,2), 
	"ESTAT_FINALITZACIO" NUMBER(*,0), 
	"DT_FASE" NUMBER(*,0), 
	"DT_FI_EXPEDIENT" NUMBER(*,0), 
	"DT_INI_EXPEDIENT" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;
--------------------------------------------------------
--  Constraints for Table FS_GIM_EXPEDIENT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_GEOLOCALITZACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_ESTAT_TRAMITACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_FASE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_AGENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_PRECEPTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_SUBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("WID_ENS" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("DT_ETL_DIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GIM_EXPEDIENT" MODIFY ("DT_ETL" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table F_GIM_EXPEDIENT
--------------------------------------------------------
DROP TABLE "DWH_FI"."F_GIM_EXPEDIENT";

  CREATE TABLE "DWH_FI"."F_GIM_EXPEDIENT" 
   (	"DT_ETL" NUMBER(*,0), 
	"DT_ETL_DIA" VARCHAR2(20 BYTE), 
	"ANY_EXPEDIENT" NUMBER(*,0), 
	"NUM_EXPEDIENT" NUMBER(*,0), 
	"WID_ENS" NUMBER(*,0) DEFAULT -1, 
	"WID_SUBJECTE" NUMBER(*,0) DEFAULT -1, 
	"WID_PRECEPTE" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOGRAFIA" NUMBER(*,0) DEFAULT -1, 
	"WID_AGENT" NUMBER(*,0) DEFAULT -1, 
	"WID_FASE" NUMBER(*,0) DEFAULT -1, 
	"WID_ESTAT_TRAMITACIO" NUMBER(*,0) DEFAULT -1, 
	"WID_GEOLOCALITZACIO" NUMBER(*,0) DEFAULT -1, 
	"DT_DENUNCIA" NUMBER(*,0), 
	"HORA_DENUNCIA" VARCHAR2(12 BYTE), 
	"FHORA_DENUNCIA" VARCHAR2(2 BYTE), 
	"DES_MARCA" VARCHAR2(40 BYTE), 
	"ID_MATRICULA" VARCHAR2(12 BYTE), 
	"TIPUS_DENUNCIA" NUMBER(*,0), 
	"CASA_DE" VARCHAR2(15 BYTE),
    "NUM_BUTLLETI" NUMBER(10,0), 
	"I_DEUTE" NUMBER(11,2), 
	"I_SANCIO" NUMBER(11,2), 
	"I_PAGAT" NUMBER(11,2), 
	"ESTAT_FINALITZACIO" NUMBER(*,0), 
	"DT_FASE" NUMBER(*,0), 
	"DT_FI_EXPEDIENT" NUMBER(*,0), 
	"DT_INI_EXPEDIENT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" 
  PARTITION BY LIST ("DT_ETL") 
 (PARTITION "LOAD_20191104"  VALUES ('20191104') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ) ;
--------------------------------------------------------
--  Constraints for Table F_GIM_EXPEDIENT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_GEOLOCALITZACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_ESTAT_TRAMITACIO" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_FASE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_AGENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_PRECEPTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_SUBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("WID_ENS" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("DT_ETL_DIA" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GIM_EXPEDIENT" MODIFY ("DT_ETL" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table TMP_GIM_EXPEDIENT_AMPLIADA
--------------------------------------------------------
DROP TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA";

  CREATE TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" 
   (	"ID_ENS" NUMBER(*,0), 
	"ANY_EXP" NUMBER(*,0), 
	"NUM_EXP" NUMBER(*,0), 
	"ID_MATRICULA" VARCHAR2(12 BYTE), 
	"DES_MARCA" VARCHAR2(40 BYTE), 
	"TIPUS_DENUNCIA" NUMBER(*,0), 
	"DES_AGENT" VARCHAR2(40 BYTE), 
	"DT_DENUNCIA" NUMBER(*,0), 
	"HORA_DENUNCIA" VARCHAR2(8 BYTE), 
	"ID_VIAL" NUMBER(*,0), 
	"CASA_DE" VARCHAR2(15 BYTE), 
    "NUM_BUTLLETI" NUMBER(10,0), 
	"ID_FASE" NUMBER(*,0), 
	"I_SANCIO" NUMBER(*,0), 
	"I_DEUTE" NUMBER(*,0), 
	"I_PAGAT" NUMBER(*,0), 
	"LITERAL" VARCHAR2(25 BYTE), 
	"NOM_COMPLET" VARCHAR2(100 BYTE), 
	"ESTAT_TRAMITACIO" NUMBER(*,0), 
	"ESTAT_FINALITZACIO" NUMBER(*,0), 
	"DT_FASE" NUMBER(*,0), 
	"DT_FI_EXPEDIENT" NUMBER(*,0), 
	"DT_INI_EXPEDIENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;
--------------------------------------------------------
--  Constraints for Table TMP_GIM_EXPEDIENT_AMPLIADA
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("NOM_COMPLET" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("LITERAL" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("ID_FASE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("ID_VIAL" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("DES_AGENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("NUM_EXP" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("ANY_EXP" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."TMP_GIM_EXPEDIENT_AMPLIADA" MODIFY ("ID_ENS" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table DS_GPP_EXP_FASES
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPP_EXP_FASES" 
   (	"ID_FASE" NUMBER(5,0), 
	"DES_FASE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPP_EXP_FASES
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPP_EXP_FASES" MODIFY ("ID_FASE" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPP_EXP_FASES
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPP_EXP_FASES" 
   (	"WID_FASE" NUMBER(38,0), 
    "ID_FASE" NUMBER(5,0), 
	"DES_FASE" VARCHAR2(100 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPP_EXP_FASES
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPP_EXP_FASES" MODIFY ("WID_FASE" NOT NULL ENABLE);
    
  INSERT INTO "DWH_FI"."D_GPP_EXP_FASES" (WID_FASE, ID_FASE, DES_FASE)
  VALUES (-1,-1,'Desconegut');
  
--------------------------------------------------------
--  DDL for Table DS_GPP_TIPUS
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPP_TIPUS" 
   (	"ID_TIPUS" NUMBER(2,0), 
	"DES_TIPUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPP_TIPUS
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPP_TIPUS" MODIFY ("ID_TIPUS" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPP_TIPUS
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPP_TIPUS" 
   (	"WID_TIPUS" NUMBER(38,0), 
    "ID_TIPUS" NUMBER(2,0), 
	"DES_TIPUS" VARCHAR2(30 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPP_TIPUS
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPP_TIPUS" MODIFY ("WID_TIPUS" NOT NULL ENABLE);
  
  INSERT INTO "DWH_FI"."D_GPP_TIPUS" (WID_TIPUS, ID_TIPUS, DES_TIPUS)
  VALUES (-1,-1,'Desconegut');
  
--------------------------------------------------------
--  DDL for Table DS_GPP_ESTAT
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPP_ESTAT" 
   (	"ID_ESTAT" NUMBER(2,0), 
	"DES_ESTAT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPP_ESTAT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPP_ESTAT" MODIFY ("ID_ESTAT" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPP_ESTAT
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPP_ESTAT" 
   (	"WID_ESTAT" NUMBER(38,0), 
    "ID_ESTAT" NUMBER(2,0), 
	"DES_ESTAT" VARCHAR2(30 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPP_ESTAT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPP_ESTAT" MODIFY ("WID_ESTAT" NOT NULL ENABLE);
  
  INSERT INTO "DWH_FI"."D_GPP_ESTAT" (WID_ESTAT, ID_ESTAT, DES_ESTAT)
  VALUES (-1,-1,'Desconegut');
  
--------------------------------------------------------
--  DDL for Table DS_GPP_EXP_CANAL
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPP_EXP_CANAL" 
   (	"ID_CANAL" NUMBER(2,0), 
	"DES_CANAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPP_EXP_CANAL
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPP_EXP_CANAL" MODIFY ("ID_CANAL" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPP_EXP_CANAL
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPP_EXP_CANAL" 
   (	"WID_CANAL" NUMBER(38,0), 
    "ID_CANAL" NUMBER(2,0), 
	"DES_CANAL" VARCHAR2(30 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPP_EXP_CANAL
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPP_EXP_CANAL" MODIFY ("WID_CANAL" NOT NULL ENABLE);
  
  INSERT INTO "DWH_FI"."D_GPP_EXP_CANAL" (WID_CANAL, ID_CANAL, DES_CANAL)
  VALUES (-1,-1,'Desconegut');
  
--------------------------------------------------------
--  DDL for Table DS_GPP_EXP_OPERACIO
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPP_EXP_OPERACIO" 
   (	"ID_OPERACIO" NUMBER(1,0), 
	"DES_OPERACIO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPP_EXP_OPERACIO
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPP_EXP_OPERACIO" MODIFY ("ID_OPERACIO" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPP_EXP_OPERACIO
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPP_EXP_OPERACIO" 
   (	"WID_OPERACIO" NUMBER(38,0), 
    "ID_OPERACIO" NUMBER(1,0), 
	"DES_OPERACIO" VARCHAR2(30 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPP_EXP_OPERACIO
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPP_EXP_OPERACIO" MODIFY ("WID_OPERACIO" NOT NULL ENABLE);
  
  INSERT INTO "DWH_FI"."D_GPP_EXP_OPERACIO" (WID_OPERACIO, ID_OPERACIO, DES_OPERACIO)
  VALUES (-1,-1,'Desconegut');
--------------------------------------------------------
--  DDL for Table DS_GPP_EXP_SUBJECTE
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPP_EXP_SUBJECTE" 
   (    "ID_SUBJECTE" NUMBER(8,0),
    "ID_PROVINCIA" VARCHAR2(5 BYTE),
    "DES_PROVINCIA" VARCHAR2(40 BYTE),
    "ID_EMISSOR" VARCHAR2(5 BYTE),
    "TIPUS" NUMBER(1,0), 
    "CP" VARCHAR2(10 BYTE),
	"ADRECA_COMPLETA"  VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;
--------------------------------------------------------
--  Constraints for Table DS_GPP_EXP_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPP_EXP_SUBJECTE" MODIFY ("ID_SUBJECTE" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table D_GPP_EXP_SUBJECTE
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPP_EXP_SUBJECTE" 
   (    "WID_SUBJECTE" NUMBER(38,0),
    "ID_SUBJECTE" NUMBER(8,0),
    "ID_PROVINCIA" VARCHAR2(5 BYTE),
    "DES_PROVINCIA" VARCHAR2(40 BYTE),
    "ID_EMISSOR" VARCHAR2(5 BYTE),
    "TIPUS" NUMBER(1,0), 
    "CP" VARCHAR2(10 BYTE),
	"ADRECA_COMPLETA"  VARCHAR2(200 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;
--------------------------------------------------------
--  Constraints for Table D_GPP_EXP_SUBJECTE
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPP_EXP_SUBJECTE" MODIFY ("WID_SUBJECTE" NOT NULL ENABLE);
  
  INSERT INTO "DWH_FI"."D_GPP_EXP_SUBJECTE" (WID_SUBJECTE, ID_SUBJECTE)
  VALUES (-1,-1);


--------------------------------------------------------
--  DDL for Table DS_GPA_EXP_FASES
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPA_EXP_FASES" 
   (	"ID_FASE" NUMBER(5,0), 
	"DES_FASE" VARCHAR2(100 BYTE),
    "ID_FASE_GRUP" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPA_EXP_FASES
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPA_EXP_FASES" MODIFY ("ID_FASE" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPA_EXP_FASES
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPA_EXP_FASES" 
   (	"WID_FASE" NUMBER(38,0), 
    "ID_FASE" NUMBER(5,0), 
	"DES_FASE" VARCHAR2(100 BYTE),
    "WID_FASE_GRUP" NUMBER(38,0),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPA_EXP_FASES
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPA_EXP_FASES" MODIFY ("WID_FASE" NOT NULL ENABLE);
  
INSERT INTO "DWH_FI"."D_GPA_EXP_FASES" (WID_FASE, ID_FASE, DES_FASE)
  VALUES (-1,-1,'Desconegut');
  
--------------------------------------------------------
--  DDL for Table DS_GPA_EXP_FASES_GRUP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."DS_GPA_EXP_FASES_GRUP" 
   (	"ID_FASE_GRUP" NUMBER(5,0), 
	"DES_FASE_GRUP" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table DS_GPA_EXP_FASES_GRUP
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."DS_GPA_EXP_FASES_GRUP" MODIFY ("ID_FASE_GRUP" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table D_GPA_EXP_FASES_GRUP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."D_GPA_EXP_FASES_GRUP" 
   (	"WID_FASE_GRUP" NUMBER(38,0), 
    "ID_FASE_GRUP" NUMBER(5,0), 
	"DES_FASE_GRUP" VARCHAR2(100 BYTE),
    "VERSION_NUMBER" NUMBER(*,0), 
	"DT_FROM" TIMESTAMP (6), 
	"DT_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table D_GPA_EXP_FASES_GRUP
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."D_GPA_EXP_FASES_GRUP" MODIFY ("WID_FASE_GRUP" NOT NULL ENABLE);
  
  INSERT INTO "DWH_FI"."D_GPA_EXP_FASES_GRUP" (WID_FASE_GRUP, ID_FASE_GRUP, DES_FASE_GRUP)
  VALUES (-1,-1,'Desconegut');

  
  
--------------------------------------------------------
--  DDL for Table FS_GPP_GPP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."FS_GPP_GPP" 
   (	"ID_GPP" NUMBER(10,0),
    "WID_GPP" NUMBER(38,0), 
	"WID_TIPUS" NUMBER(38,0), 
    "WID_ESTAT" NUMBER(38,0),
    "DATA_INICI" DATE,
    "DATA_FI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPP_GPP
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."FS_GPP_GPP" MODIFY ("WID_GPP" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table F_GPP_GPP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."F_GPP_GPP" 
   (    "ID_GPP" NUMBER(10,0),	
    "WID_GPP" NUMBER(38,0), 
	"WID_TIPUS" NUMBER(38,0), 
    "WID_ESTAT" NUMBER(38,0),
    "DATA_INICI" DATE,
    "DATA_FI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table F_GPP_GPP
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."F_GPP_GPP" MODIFY ("WID_GPP" NOT NULL ENABLE);
  
  
--------------------------------------------------------
--  DDL for Table FS_GPP_EXP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."FS_GPP_EXP" 
   (	"WID_EXPEDIENT" NUMBER(38,0), 
        "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_EXPEDIENT" NUMBER(38,0), 
    "WID_GPP" NUMBER(38,0), 
	"WID_FASE" NUMBER(38,0),
    "DATA_FASE" DATE, 
    "WID_CANAL" NUMBER(38,0),
    "WID_OPERACIO" NUMBER(38,0),
    "WID_SUBJECTE" NUMBER(38,0),
    "DATA_INICI" DATE,
    "DATA_FI" DATE,
    "ANY_EFECTIU" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPP_EXP
--------------------------------------------------------
  ALTER TABLE "DWH_FI"."FS_GPP_EXP" MODIFY ("WID_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPP_EXP" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPP_EXP" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table F_GPP_EXP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."F_GPP_EXP" 
   (	"WID_EXPEDIENT" NUMBER(38,0), 
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_EXPEDIENT" NUMBER(38,0), 
    "WID_GPP" NUMBER(38,0), 
	"WID_FASE" NUMBER(38,0), 
    "DATA_FASE" DATE, 
    "WID_CANAL" NUMBER(38,0),
    "WID_OPERACIO" NUMBER(38,0),
    "WID_SUBJECTE" NUMBER(38,0),
    "DATA_INICI" DATE,
    "DATA_FI" DATE,
    "ANY_EFECTIU" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPP_GPP
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."F_GPP_EXP" MODIFY ("WID_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPP_EXP" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPP_EXP" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  
  
  
--------------------------------------------------------
--  DDL for Table FS_GPP_EXP_OBJECTE
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."FS_GPP_EXP_OBJECTE" 
   (	"WID_OBJECTE" NUMBER(38,0), 
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_OBJECTE" NUMBER(38,0), 
    "WID_TRIBUT" NUMBER(38,0), 
    "NUM_FIXE" VARCHAR2(30 BYTE), 
    "IMPORT" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPP_EXP_OBJECTE
--------------------------------------------------------
    ALTER TABLE "DWH_FI"."FS_GPP_EXP_OBJECTE" MODIFY ("WID_OBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPP_EXP_OBJECTE" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPP_EXP_OBJECTE" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPP_EXP_OBJECTE" MODIFY ("WID_TRIBUT" NOT NULL ENABLE);
  


--------------------------------------------------------
--  DDL for Table F_GPP_EXP_OBJECTE
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."F_GPP_EXP_OBJECTE" 
   (	"WID_OBJECTE" NUMBER(38,0),
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_OBJECTE" NUMBER(38,0), 
    "WID_TRIBUT" NUMBER(38,0), 
    "NUM_FIXE" VARCHAR2(30 BYTE), 
    "IMPORT" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table F_GPP_EXP_OBJECTE
--------------------------------------------------------
    ALTER TABLE "DWH_FI"."F_GPP_EXP_OBJECTE" MODIFY ("WID_OBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPP_EXP_OBJECTE" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPP_EXP_OBJECTE" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPP_EXP_OBJECTE" MODIFY ("WID_TRIBUT" NOT NULL ENABLE);
  
  
--------------------------------------------------------
--  DDL for Table FS_GPA_EXP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."FS_GPA_EXP" 
   (	"WID_EXPEDIENT" NUMBER(38,0),
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_EXPEDIENT" NUMBER(38,0), 
    "WID_GPP" NUMBER(38,0), 
	"WID_FASE" NUMBER(38,0), 
    "DATA_FASE" DATE,
    "WID_SUBJECTE" NUMBER(38,0),
    "DATA_INICI" DATE,
    "DATA_FI" DATE,
    "EXERCICI" NUMBER(4,0),
    "IMPORT_ACUMULAT" NUMBER(11,0),
    "IMPORT_IMPAGAT" NUMBER(11,0),
    "IMPORT_ANULAT" NUMBER(11,0),
    "IMPORT_PENDENT" NUMBER(11,0),
    "IMPORT_DEVOLUCIO" NUMBER(11,0),
    "IMPORT_TOTAL" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPA_EXP
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."FS_GPA_EXP" MODIFY ("WID_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table F_GPA_EXP
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."F_GPA_EXP" 
   (	"WID_EXPEDIENT" NUMBER(38,0),
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_EXPEDIENT" NUMBER(38,0), 
    "WID_GPP" NUMBER(38,0), 
	"WID_FASE" NUMBER(38,0), 
    "DATA_FASE" DATE,
    "WID_SUBJECTE" NUMBER(38,0),
    "DATA_INICI" DATE,
    "DATA_FI" DATE,
    "EXERCICI" NUMBER(4,0),
    "IMPORT_ACUMULAT" NUMBER(11,0),
    "IMPORT_IMPAGAT" NUMBER(11,0),
    "IMPORT_ANULAT" NUMBER(11,0),
    "IMPORT_PENDENT" NUMBER(11,0),
    "IMPORT_DEVOLUCIO" NUMBER(11,0),
    "IMPORT_TOTAL" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table F_GPA_EXP
--------------------------------------------------------
    ALTER TABLE "DWH_FI"."F_GPA_EXP" MODIFY ("WID_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  
  
  
--------------------------------------------------------
--  DDL for Table FS_GPA_EXP_OBJECTE
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE" 
   (	"WID_OBJECTE" NUMBER(38,0),
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_OBJECTE" NUMBER(38,0), 
    "WID_TRIBUT" NUMBER(38,0), 
    "NUM_FIXE" VARCHAR2(30 BYTE), 
    "IMPORT_ACUMULAT" NUMBER(11,0),
    "IMPORT_OBJECTE" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPA_EXP_OBJECTE
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE" MODIFY ("WID_OBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE" MODIFY ("WID_TRIBUT" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table F_GPA_EXP_OBJECTE
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."F_GPA_EXP_OBJECTE" 
   (	"WID_OBJECTE" NUMBER(38,0),
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_OBJECTE" NUMBER(38,0), 
    "WID_TRIBUT" NUMBER(38,0), 
    "NUM_FIXE" VARCHAR2(30 BYTE), 
    "IMPORT_ACUMULAT" NUMBER(11,0),
    "IMPORT_OBJECTE" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table F_GPA_EXP_OBJECTE
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE" MODIFY ("WID_OBJECTE" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE" MODIFY ("WID_TRIBUT" NOT NULL ENABLE);
  
  
--------------------------------------------------------
--  DDL for Table FS_GPA_EXP_OBJECTE_REBUT
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE_REBUT" 
   (	"WID_REBUT" NUMBER(38,0), 
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_OBJECTE" NUMBER(38,0), 
    "WID_TRIBUT" NUMBER(38,0), 
    "NUM_FIXE" VARCHAR2(30 BYTE), 
    "ID_REBUT" NUMBER(8,0), 
    "ID_ESTAT_REBUT" NUMBER(2,0), 
    "DES_ESTAT_REBUT" VARCHAR2(100 BYTE),
    "IMPORT_REBUT" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table FS_GPA_EXP_OBJECTE_REBUT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE_REBUT" MODIFY ("WID_REBUT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE_REBUT" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE_REBUT" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE_REBUT" MODIFY ("WID_TRIBUT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."FS_GPA_EXP_OBJECTE_REBUT" MODIFY ("ID_REBUT" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table F_GPA_EXP_OBJECTE_REBUT
--------------------------------------------------------

  CREATE TABLE "DWH_FI"."F_GPA_EXP_OBJECTE_REBUT" 
   (	"WID_REBUT" NUMBER(38,0),
    "ANY_EXPEDIENT" NUMBER(4,0), 
    "NUM_EXPEDIENT" NUMBER(9,0),
    "WID_ENS_OBJECTE" NUMBER(38,0), 
    "WID_TRIBUT" NUMBER(38,0), 
    "NUM_FIXE" VARCHAR2(30 BYTE), 
    "ID_REBUT" NUMBER(8,0), 
    "ID_ESTAT_REBUT" NUMBER(2,0), 
    "DES_ESTAT_REBUT" VARCHAR2(100 BYTE),
    "IMPORT_REBUT" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_DATA" ;


--------------------------------------------------------
--  Constraints for Table F_GPA_EXP_OBJECTE_REBUT
--------------------------------------------------------

  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE_REBUT" MODIFY ("WID_REBUT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE_REBUT" MODIFY ("ANY_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE_REBUT" MODIFY ("NUM_EXPEDIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE_REBUT" MODIFY ("WID_TRIBUT" NOT NULL ENABLE);
  ALTER TABLE "DWH_FI"."F_GPA_EXP_OBJECTE_REBUT" MODIFY ("ID_REBUT" NOT NULL ENABLE);